name: Deploy Document

on:
  push:
    branches:
      - docs
  workflow_dispatch:
    inputs:
      nothing:
        description: 'This param do nothing'     
        required: false
        type: boolean
        default: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: docs
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci

      - name: Build
        run: npm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
      - name: Sync Push to Gitee
        env:
            GITEE_AUTH: ${{ secrets.GITEE_AUTH }}
        if: ${{ env.GITEE_AUTH != ''}}
        run: |
            echo "https://$GITEE_AUTH@gitee.com/" > .credential
            git config --local credential.helper "store --file=.credential"
            git remote add gitee https://gitee.com/NiceLeee/BilibiliDown.git
            branch_name=`git rev-parse --abbrev-ref HEAD`
            git push -f gitee "$branch_name"
            rm -f .credential